export const SocketEvents = {
  CREATE_A_ROOM: "create-a-room",
  JOIN_A_ROOM: "join-a-room",
  SEND_PLAYER_INFOS: "send-player-infos",
  PLAYER_JOIN_YOUR_ROOM: "player-join-your-room",
  FIND_THE_ROOM: "find-the-room",
  ROOM_CREATED: "room-created",
  ROOM_READY: "room-ready",
  BATTLE_BEGIN: "battle-begin",
  HIT: "hit",
  SPELL: "spell",
  UPDATE_BATTLE_STATE: "update-battle-state",
  BATTLE_FINISH: "battle-finish",
  JOIN_THE_QUEUE: "join-the-queue",
};
